# Generated by Django 2.2 on 2019-05-06 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_title', models.CharField(max_length=100)),
                ('forum_mode', models.IntegerField()),
                ('forum_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pic', models.CharField(max_length=200)),
                ('user_age', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=5000)),
                ('post_pub_date', models.DateTimeField(verbose_name='Data de publicação')),
                ('post_likes', models.IntegerField(default=0)),
                ('post_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Forum')),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.ForumUser')),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='forum_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.ForumUser'),
        ),
    ]
