# Generated by Django 2.2 on 2019-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumuser',
            name='user_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
